name: Teste Python

on:
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Instala Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Executa seu script
        run: |
          python .github/workflows/historico_justificativa.py

      - name: Upload do Excel gerado
        uses: actions/upload-artifact@v4
        with:
          name: resultado-excel
          path: historico_justificativa_teste.xlsx
