name: Teste Python

on:
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Instala Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Executa script de teste
        run: |
          echo "Rodando no GitHub Actions"
          python -c "print('Funcionou!')"
